name: Build TV

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths-ignore:
      - "**.md"
  workflow_dispatch:
    inputs:
      tag:
        description: "Release Tag (如 v1.0.0)"
        required: false
        default: ""

jobs:
  android_tv:
    if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
    name: Build Android TV
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Remove Android directory
        run: rm -rf android

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Create Android project
        run: |
          flutter create --org com.example --project-name piliplus .

      - name: Modify package name and app label
        run: |
          # 修改包名
          sed -i 's/com.example.piliplus/com.example.piliplus.tv/g' android/app/src/main/AndroidManifest.xml
          sed -i 's/com.example.piliplus/com.example.piliplus.tv/g' android/app/build.gradle.kts
          # 修改应用名称
          sed -i 's/android:label="piliplus"/android:label="PiliPlus TV"/g' android/app/src/main/AndroidManifest.xml

      - run: flutter pub get

      - name: Set version
        if: github.event.inputs.tag != ''
        run: echo "VERSION=${{ github.event.inputs.tag }}" >> $GITHUB_ENV

      - run: flutter build apk --release
        if: github.event_name == 'workflow_dispatch'

      - run: flutter build apk --release --dart-define=dev=1
        if: github.event_name == 'pull_request'

      - uses: actions/upload-artifact@v7
        with:
          name: PiliPlus_TV_${{ env.VERSION || 'dev' }}
          path: build/app/outputs/flutter-apk/app-*.apk
