name: Build For TV

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths-ignore:
      - "**.md"
  workflow_dispatch:
    inputs:
      build_tv:
        description: "Build For TV"
        required: false
        default: true
        type: boolean

      tag:
        description: "版本号(例如v1.0，填写将创建Release)"
        required: false
        default: ""
        type: string

jobs:
  tv:
    if: ${{ (github.event_name == 'pull_request' && github.repository == 'bggRGjQaUbCoE/PiliPlus') || github.event.inputs.build_tv == 'true' }}
    name: Release TV
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: "17"
          cache: gradle
          cache-dependency-path: |
            android/*.gradle*
            android/**/gradle-wrapper.properties

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          cache: true

      - name: Apply Patch
        shell: pwsh
        run: lib/scripts/patch.ps1 android
        continue-on-error: true

      - name: Write key
        if: github.event_name == 'workflow_dispatch'
        run: |
          if [ -n "${{ secrets.SIGN_KEYSTORE_BASE64 }}" ]; then
            echo "${{ secrets.SIGN_KEYSTORE_BASE64 }}" | base64 --decode > android/app/key.jks
            cat > android/key.properties <<EOF
storeFile=key.jks
storePassword=${{ secrets.KEYSTORE_PASSWORD }}
keyAlias=${{ secrets.KEY_ALIAS }}
keyPassword=${{ secrets.KEY_PASSWORD }}
EOF
          fi

      - name: Set version
        if: github.event_name == 'workflow_dispatch'
        shell: pwsh
        run: lib/scripts/build.ps1 android

      - name: Build Release APK
        if: github.event_name == 'workflow_dispatch'
        run: flutter build apk --release --flavor tv --split-per-abi --dart-define-from-file=pili_release.json --pub

      - name: Build Dev APK (PR)
        if: github.event_name == 'pull_request'
        run: flutter build apk --release --flavor tv --split-per-abi --android-project-arg dev=1 --pub

      - name: Rename APK
        run: |
          cd build/app/outputs/flutter-apk
          for file in app-tv-*-release.apk; do
            if [ -f "$file" ]; then
              abi=$(echo "$file" | sed -E 's/.*app-tv-(.*)-release\.apk/\1/')
              mv -v "$file" "../../../PiliPlus_TV_${{ env.version }}_${abi}.apk"
            fi
          done

      - name: Create Release
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.tag != ''
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: "TV ${{ github.event.inputs.tag }}"
          files: PiliPlus_TV_*.apk

      - name: Upload arm64-v8a
        uses: actions/upload-artifact@v7
        with:
          archive: false
          name: TV_arm64-v8a
          path: PiliPlus_TV_*_arm64-v8a.apk

      - name: Upload armeabi-v7a
        uses: actions/upload-artifact@v7
        with:
          archive: false
          name: TV_armeabi-v7a
          path: PiliPlus_TV_*_armeabi-v7a.apk

      - name: Upload x86_64
        uses: actions/upload-artifact@v7
        with:
          archive: false
          name: TV_x86_64
          path: PiliPlus_TV_*_x86_64.apk
