name: Build TV (Multi-ABI)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release Tag"
        required: false
        default: ""

jobs:
  android_tv:
    name: Build Android TV (Multi-ABI)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Remove Android directory
        run: rm -rf android

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - run: flutter create --org com.example --project-name piliplus .

      - run: flutter pub get

      - run: flutter build apk --release --split-per-abi

      - name: Rename APKs
        run: |
          for file in build/app/outputs/flutter-apk/app-*-release.apk; do
            abi=$(echo "$file" | sed -E 's|.*app-(.*)-release\.apk|\1|')
            mv "$file" "PiliPlus_TV_${abi}.apk"
          done

      - name: Set version
        if: github.event.inputs.tag != ''
        run: echo "version=$(date +%Y%m%d-%H%M)" >> $GITHUB_ENV

      - name: Upload arm64-v8a
        uses: actions/upload-artifact@v7
        with:
          name: PiliPlus_TV_arm64-v8a
          path: PiliPlus_TV_arm64-v8a.apk

      - name: Upload armeabi-v7a
        uses: actions/upload-artifact@v7
        with:
          name: PiliPlus_TV_armeabi-v7a
          path: PiliPlus_TV_armeabi-v7a.apk

      - name: Upload x86_64
        uses: actions/upload-artifact@v7
        with:
          name: PiliPlus_TV_x86_64
          path: PiliPlus_TV_x86_64.apk
